// Code generated by gocc; DO NOT EDIT.

package token

import (
	"fmt"
)

type Token struct {
	Type
	Lit []byte
	Pos
}

type Type int

const (
	INVALID Type = iota
	EOF
)

type Pos struct {
	Offset int
	Line   int
	Column int
}

func (p Pos) String() string {
	return fmt.Sprintf("Pos(offset=%d, line=%d, column=%d)", p.Offset, p.Line, p.Column)
}

type TokenMap struct {
	typeMap []string
	idMap   map[string]Type
}

func (m TokenMap) Id(tok Type) string {
	if int(tok) < len(m.typeMap) {
		return m.typeMap[tok]
	}
	return "unknown"
}

func (m TokenMap) Type(tok string) Type {
	if typ, exist := m.idMap[tok]; exist {
		return typ
	}
	return INVALID
}

func (m TokenMap) TokenString(tok *Token) string {
	//TODO: refactor to print pos & token string properly
	return fmt.Sprintf("%s(%d,%s)", m.Id(tok.Type), tok.Type, tok.Lit)
}

func (m TokenMap) StringType(typ Type) string {
	return fmt.Sprintf("%s(%d)", m.Id(typ), typ)
}

var TokMap = TokenMap{
	typeMap: []string{
		"INVALID",
		"$",
		"assign",
		"atleast",
		"atmost",
		"class",
		"colon",
		"comma",
		"def",
		"div",
		"elif",
		"else",
		"eq",
		"extends",
		"false",
		"gt",
		"ident",
		"if",
		"int",
		"lbrace",
		"let",
		"lparen",
		"lt",
		"minus",
		"mul",
		"period",
		"plus",
		"rbrace",
		"return",
		"rparen",
		"semicolon",
		"string_literal",
		"true",
		"typecase",
		"while",
	},

	idMap: map[string]Type{
		"INVALID":        0,
		"$":              1,
		"assign":         2,
		"atleast":        3,
		"atmost":         4,
		"class":          5,
		"colon":          6,
		"comma":          7,
		"def":            8,
		"div":            9,
		"elif":           10,
		"else":           11,
		"eq":             12,
		"extends":        13,
		"false":          14,
		"gt":             15,
		"ident":          16,
		"if":             17,
		"int":            18,
		"lbrace":         19,
		"let":            20,
		"lparen":         21,
		"lt":             22,
		"minus":          23,
		"mul":            24,
		"period":         25,
		"plus":           26,
		"rbrace":         27,
		"return":         28,
		"rparen":         29,
		"semicolon":      30,
		"string_literal": 31,
		"true":           32,
		"typecase":       33,
		"while":          34,
	},
}
