// Code generated by gocc; DO NOT EDIT.

package token

import (
	"fmt"
)

type Token struct {
	Type
	Lit []byte
	Pos
}

type Type int

const (
	INVALID Type = iota
	EOF
)

type Pos struct {
	Offset int
	Line   int
	Column int
}

func (p Pos) String() string {
	return fmt.Sprintf("Pos(offset=%d, line=%d, column=%d)", p.Offset, p.Line, p.Column)
}

type TokenMap struct {
	typeMap []string
	idMap   map[string]Type
}

func (m TokenMap) Id(tok Type) string {
	if int(tok) < len(m.typeMap) {
		return m.typeMap[tok]
	}
	return "unknown"
}

func (m TokenMap) Type(tok string) Type {
	if typ, exist := m.idMap[tok]; exist {
		return typ
	}
	return INVALID
}

func (m TokenMap) TokenString(tok *Token) string {
	//TODO: refactor to print pos & token string properly
	return fmt.Sprintf("%s(%d,%s)", m.Id(tok.Type), tok.Type, tok.Lit)
}

func (m TokenMap) StringType(typ Type) string {
	return fmt.Sprintf("%s(%d)", m.Id(typ), typ)
}

var TokMap = TokenMap{
	typeMap: []string{
		"INVALID",
		"$",
		"empty",
		"class",
		"ident",
		"lparen",
		"rparen",
		"extends",
		"colon",
		"comma",
		"lbrace",
		"rbrace",
		"def",
		"if",
		"while",
		"assign",
		"semicolon",
		"return",
		"elif",
		"else",
		"period",
		"string_literal",
		"plus",
		"minus",
		"atleast",
		"atmost",
		"lt",
		"gt",
		"and",
		"or",
		"not",
		"mul",
		"div",
		"int",
		"true",
		"false",
		"typecase",
		"eq",
		"let",
		"string_escape_error",
		"unknown",
	},

	idMap: map[string]Type{
		"INVALID":             0,
		"$":                   1,
		"empty":               2,
		"class":               3,
		"ident":               4,
		"lparen":              5,
		"rparen":              6,
		"extends":             7,
		"colon":               8,
		"comma":               9,
		"lbrace":              10,
		"rbrace":              11,
		"def":                 12,
		"if":                  13,
		"while":               14,
		"assign":              15,
		"semicolon":           16,
		"return":              17,
		"elif":                18,
		"else":                19,
		"period":              20,
		"string_literal":      21,
		"plus":                22,
		"minus":               23,
		"atleast":             24,
		"atmost":              25,
		"lt":                  26,
		"gt":                  27,
		"and":                 28,
		"or":                  29,
		"not":                 30,
		"mul":                 31,
		"div":                 32,
		"int":                 33,
		"true":                34,
		"false":               35,
		"typecase":            36,
		"eq":                  37,
		"let":                 38,
		"string_escape_error": 39,
		"unknown":             40,
	},
}
